### ISSUE TITLE
Serious Sam Next Encounter PS2 and GameCube Codes

### ISSUE THREAD

**Issue by SpaceCat9** [YukiXXL/PS2-modding#5]
Hi YukiXXL,

Following from the YouTube thread, are you able to post the Cheat Codes for Serious Sam Next Encounter here?

If no, no worries, but thanks for trying.

**Comment by YukiXXL** [comment]
GameCube codes (PAL version): https://www.gc-forever.com/forums/viewtopic.php?t=1964

PS2 codes (PAL version):

Action Replay MAX:

Mastercode
P79B-TVF0-C17E1
GKT7-DFE9-ZAMY8
0GTN-0KYE-1UBBT

Run "Init Menu" at the start
2P1Z-2EV5-MTFUC
KTJK-ABRG-72BHH

Gameshark V5:

Mastercode
760235F0 00000000
902FABEC 0C0C46CD

Run "Init Menu" at the start
760771B0 00000000
00277408 24040006

**Comment by YukiXXL** [comment]
If you find out what version of Cheat Device you are using, I wrote a guide on converting them. It is at the beginning of this repository.

**Comment by SpaceCat9** [comment]
Thanks so much
And separately from a console, would this work on an emulator (PCXS2)?

**Comment by YukiXXL** [comment]
Yes. All the codes made are for PCSX2.
